#This is a Secret resource with a randomly generated password in its SecretString JSON.
Resources:
  MySecretA:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: MySecretForAppA
      Description: "This secret has a dynamically generated secret password."
      GenerateSecretString:
        SecretStringTemplate: '{"username": "test-user"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludeCharacters: '"@/\'
      Tags:
        -
          Key: AppName
          Value: AppA
Outputs:
  StackName:
    Value: !Ref 'AWS::StackName'
  Arn:
    Value: !Ref 'MySecretA'
    Export:
      Name: 'Secretexport'
